
name: cd

on:
  push:
    branches: [ workitem4_splitmain2ci-and-cd ]
    
#starting buildjob
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:  
      - name: artifact download
        uses: download-artifact@v2
        with:
         name: my-artifact
         path: ${{ github.workspace }}
         
      - name: checking download file
        run: |
          pwd
          ls
          
      - name: step to deploy CF
        run: |
         wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
         echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
         sudo apt-get update
         sudo apt-get install cf8-cli
         cf login -a https://api.cf.ap21.hana.ondemand.com -u ramyaravindra999@gmail.com -p ${{ secrets.CF_PASSWORD }} -o 6fece677trial -s prod
         #cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USERNAME }}m -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORGANISATION }} -s ${{ secrets.CF_SPACE }}
         pwd
         cd build
         cd libs
         pwd
         cf push test -p gradle-github-actions-example.jar --no-route
         
